version: '3.9'

services:

  db:
    image: mysql:8.0.30
    container_name: MySQL
    restart: always
    volumes:
      - .docker/mysql/data/:/var/lib/mysql
      - .docker/mysql/my.cnf:/etc/my.cnf
      - .docker/mysql/dump/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306

  web:
    container_name: Web
    restart: always
    build: .docker/php/
    depends_on:
      - db
    volumes:
       - .:/var/www/html/
       - .docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
       - .docker/apache2/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - ${HTTP_PORT}:80

  composer:
    image: composer:2.3
    container_name: Composer
    command: ["composer", "install"]
    depends_on:
      - web
    volumes:
      - .:/app/

  redis:
    build: .docker/redis/
    container_name: Redis
    restart: always
    depends_on:
      - web

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpMyAdmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    links:
      - db
    depends_on:
      - db
      - web
    ports:
      - ${PMA_PORT}:80